config/routes.rb
Spree::Core::Engine.routes.draw do
  resources :wishlists
  resources :wished_products, only: [:create, :update, :destroy]
  get '/wishlist' => "wishlists#default", as: "default_wishlist"
end

app/models/spree/user_decorator.rb
Spree.user_class.class_eval do
  has_many :wishlists, :class_name => Spree::Wishlist

  def wishlist
    default_wishlist = self.wishlists.where(is_default: true).first
    default_wishlist ||= self.wishlists.first
    default_wishlist ||= self.wishlists.create(:name => Spree.t(:default_wishlist_name, :default => "My wishlist"), :is_default => true)
    default_wishlist.update_attribute(:is_default, true) unless default_wishlist.is_default?
    default_wishlist
  end
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  has_many :wished_products, :dependent => :destroy
end

app/models/spree/wished_product.rb
class Spree::WishedProduct < ActiveRecord::Base
  belongs_to :variant
  belongs_to :wishlist
end

app/models/spree/wishlist.rb
class Spree::Wishlist < ActiveRecord::Base
  belongs_to :user, :class_name => Spree.user_class
  has_many :wished_products
  before_create :set_access_hash

  validates :name, :presence => true

  def include?(variant_id)
    self.wished_products.map(&:variant_id).include? variant_id.to_i
  end

  def to_param
    self.access_hash
  end

  def self.get_by_param(param)
    Spree::Wishlist.find_by_access_hash(param)
  end

  def can_be_read_by?(user)
    !self.is_private? || user == self.user
  end

  def is_default=(value)
    self['is_default'] = value
    if self.is_default?
      Spree::Wishlist.where(is_default: true, user_id: self.user_id).where.not(id: self.id).update_all(is_default: false)
    end
  end

  def is_public?
    !self.is_private?
  end

  private

  def set_access_hash
    random_string = SecureRandom::hex(16)
    self.access_hash = Digest::SHA1.hexdigest("--#{user_id}--#{random_string}--#{Time.now}--")
  end
end

app/models/wishednotifier.rb
require 'sendwithus_ruby_action_mailer'
class Wishednotifier < ::SendWithUsMailer::Base

  default from: 'atendimento@dragonflyvc.com'

  def order_wished(order, email)
      assign :user, {email: email}

      assign :product, {id: order}

      mail(
          email_id: 'tem_bF4SMRBMPv2mjyV4SgZ6p3',
          recipient_address: "marcelo@versuti.com.br",
      )
  end
end

app/controllers/spree/wished_products_controller.rb
require 'sendwithus_ruby_action_mailer'

class Spree::WishedProductsController < Spree::StoreController
  respond_to :html

  def create
    @wished_product = Spree::WishedProduct.new(wished_product_attributes)
    @wishlist = spree_current_user.wishlist

    if @wishlist.include? params[:wished_product][:variant_id]
      @wished_product = @wishlist.wished_products.detect {|wp| wp.variant_id == params[:wished_product][:variant_id].to_i }
    else
      @wished_product.wishlist = spree_current_user.wishlist
      @wished_product.save
      mail = Wishednotifier.order_wished(@wished_product.variant.product.name, spree_current_user.email)
      mail.deliver
    end

    respond_with(@wished_product) do |format|
      format.html { redirect_to wishlist_url(@wishlist) }
    end
  end

  def update
    @wished_product = Spree::WishedProduct.find(params[:id])
    @wished_product.update_attributes(wished_product_attributes)

    respond_with(@wished_product) do |format|
      format.html { redirect_to wishlist_url(@wished_product.wishlist) }
    end
  end

  def destroy
    @wished_product = Spree::WishedProduct.find(params[:id])
    @wished_product.destroy

    respond_with(@wished_product) do |format|
      format.html { redirect_to wishlist_url(@wished_product.wishlist) }
    end
  end

  private

  def wished_product_attributes
    params.require(:wished_product).permit(:variant_id, :wishlist_id)
  end

end

app/controllers/spree/wishlists_controller.rb
class Spree::WishlistsController < Spree::StoreController
  helper 'spree/products'

  before_filter :find_wishlist, :only => [:destroy, :show, :update, :edit]

  respond_to :html
  respond_to :js, :only => [:update]

  def new
    @wishlist = Spree::Wishlist.new

    respond_with(@wishlist)
  end

  def index
    @wishlists = spree_current_user.wishlists

    respond_with(@wishlist)
  end

  def edit
    respond_with(@wishlist)
  end

  def update
    @wishlist.update_attributes wishlist_attributes

    respond_with(@wishlist)
  end

  def show
    respond_with(@wishlist)
  end

  def default
    @wishlist = spree_current_user.wishlist

    respond_with(@wishlist)do |format|
      format.html { render 'show' }
    end
  end

  def create
    @wishlist = Spree::Wishlist.new wishlist_attributes
    @wishlist.user = spree_current_user

    @wishlist.save
    respond_with(@wishlist)
  end

  def destroy
    @wishlist.destroy
    respond_with(@wishlist )do |format|
      format.html { redirect_to account_path }
    end
  end

  private

  def wishlist_attributes
    params.require(:wishlist).permit(:name, :is_default, :is_private)
  end

  # Isolate this method so it can be overwritten
  def find_wishlist
    @wishlist = Spree::Wishlist.find_by_access_hash(params[:id])
  end

end

app/views/spree/products/_wishlist_form.html.erb
<% if spree_current_user %>
  <div id="wishlist-form">
    <%= form_for Spree::WishedProduct.new do |f| %>
      <%= f.hidden_field :variant_id, :value => @product.master.id %>
      <button type="submit" class="large primary">
        <%= Spree.t(:add_to_wishlist) %>
      </button>
    <% end %>
  </div>
<% end %>

app/views/spree/users/_wishlists.html.erb
<h3><%= Spree.t(:default_wishlist_name) %></h3>
<div>
<ul id="mywishlist" >
<% @user.wishlists.each do |wl| %>
  <% if !wl.is_private? || @user == spree_current_user %>
  <li><%= link_to Spree.t(:see_wishlist), wl %></li>
  <% end -%>
<% end -%>
</ul>
</div>

app/views/spree/wishlists/_accessibility.html.erb
<%= form_for @wishlist, :html => {:class => 'ajax_form', :id => 'change_wishlist_accessibility'} do |f| %>
  <%= f.radio_button :is_private, true %>&nbsp;<%= Spree.t(:private) %>
  <%= f.radio_button :is_private, false %>&nbsp;<%= Spree.t(:public) %>
<% end -%>

app/views/spree/wishlists/_mail_to_friend.text.erb
<%= mail.recipient_name %>,

Please, take a look to my wishlist:

  * <%= wishlist.name %>

<% unless mail.message.blank? -%>
<%= mail.message %>
<% end -%>

<%= mail.sender_name %>

Click the link below to view the <%= wishlist.name %> page.
<%= wishlist_url(wishlist) %>

app/views/spree/wishlists/edit.html.erb
<h1 class="row"><%= Spree.t(:editing_wishlist) %></h1>
<%= form_for @wishlist do |f| %>
  <p><%= f.label :name, Spree.t(:name) %>:&nbsp;<%= f.text_field :name %></p>
  <p><%= f.check_box :is_private %>&nbsp;<%= f.label :is_private, Spree.t(:is_private) %></p>
  <p><%= f.check_box :is_default %>&nbsp;<%= f.label :is_default, Spree.t(:is_default) %></p>
  <%= f.submit Spree.t(:update) %> <%= Spree.t(:or) %> <%= link_to Spree.t(:delete_wishlist), @wishlist, :method => :delete, :confirm => Spree.t(:are_you_sure_wishlist), :class => "button" %>
<% end -%>

app/views/spree/wishlists/index.html.erb
<h1 class="row"><%= Spree.t(:wishlists) %></h1>
<%= content_tag :ul do %>
  <% @wishlists.each do |wishlist| %>
    <%= content_tag :li do %> 
      <%=  link_to(wishlist.name, wishlist) %>  - <%= wishlist.is_private ? Spree.t(:private) : Spree.t(:public)%>
    <% end %>
  <% end %>
<% end %>

app/views/spree/wishlists/new.html.erb
<h1><%= Spree.t(:creating_wishlist) %></h1>
<%= form_for @wishlist do |f| %>
  <p><%= f.label :name, Spree.t(:name) %>:&nbsp;<%= f.text_field :name %></p>
  <p><%= f.check_box :is_private %>&nbsp;<%= f.label :is_private, Spree.t(:is_private) %></p>
  <%= f.submit Spree.t(:create) %>
<% end -%>

app/views/spree/wishlists/show.html.erb
<div id="wishlist_header" class="row">
  <h1><%= Spree.t(:default_wishlist_name) %></h1>
</div>
<div id="wishlist_page" >
<table id="wishlist">
  <thead>
    <tr>
      <th><%= Spree.t(:item_view) %></th>
      <th><%= Spree.t(:item_description) %></th>
      <th><%= Spree.t(:availability) %></th>
      <th><%= Spree.t(:date_added) %></th>
      <th><%= Spree.t(:price) %></th>
      <% if @wishlist.user == spree_current_user %>
        <th><%= Spree.t(:wishlist_actions) %></th>
      <% end -%>
    </tr>
  </thead>
  <tbody id="line_items">
  <% if @wishlist.wished_products.size > 0 %>
    <% @wishlist.wished_products.each do |wish|
        variant = wish.variant
        product = variant.product %>
    <tr class="line_item">
      <td class="wishlist_image">
        <% if variant.images.length == 0 %>
          <%= small_image(variant.product) %>
        <% else %>
          <%= image_tag variant.images.first.attachment.url(:mini) %>
        <% end %>
      </td>

      <td class="wishlist_name">
        <h4><%= link_to "VISUALIZAR " + product.name, product %></h4>
        <p><%= variant_options variant %></p>
        <%= truncate(product.description, :length => 100, :omission => "...") %>
      </td>
      <td class="wishlist_availability">
        <%= variant.in_stock? ? Spree.t(:in_stock) : Spree.t(:out_of_stock) %>
      </td>
      <td class="wishlist_date">
        <%= wish.created_at.strftime "%d/%m/%Y" %>
      </td>
      <td class="wishlist_price">
        <%= number_to_currency(variant.price) %>
      </td>
      <% if @wishlist.user == spree_current_user %>
        <td class="wishlist_actions">
          <p><%= link_to Spree.t(:remove_from_wishlist), wish, :method => :delete, :class => 'button' %></p>
          <%= form_for :order, :url => populate_orders_url do |f| %>
            <%= hidden_field_tag "variants[#{variant.id}]", 1, :size => 3 %>
            <%= link_to Spree.t(:add_to_cart), '#', :onclick => "$(this).parent().submit(); return false;", :class => "button" %>
          <% end %>
          <% if spree_current_user.wishlists.count > 1 %>
            <%= Spree.t(:move_to_another_wishlist) %>:
            <%= form_for wish do |f| %>
              <%= f.select :wishlist_id, spree_current_user.wishlists.map{|wl| [wl.name, wl.id]} %>
              <%= f.submit Spree.t(:move) %>
            <% end %>
          <% end %>
          <br />
        </td>
      <% end -%>
    </tr>
    <% end -%>
  <% else -%>
    <tr>
      <td colspan="6"><%= Spree.t(:your_wishlist_is_empty) %></td>
    </tr>
  <% end -%>
  </tbody>
</table>
<div class="footer_links" data-hook="wishlist_footer_links">
<%= link_to Spree.t(:continue_shopping), products_path, :class => "button" %>
<% if respond_to?(:email_to_friend_url) %>
  <%= link_to Spree.t('email_to_friend.send_to_friend'), email_to_friend_url('wishlist', @wishlist), :class => "button" %>
<% end %>
</div>

</div>